steps:
  - name: python
    id: "Setup Python"
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt" , "--user"]
  - name: python
    id: "black"
    entrypoint: python
    args: ["-m", "black", "src", "--check"]
  - name: python
    id: "isort"
    entrypoint: python
    args: ["-m", "isort", "src", "--check-only",  "--profile", "black"]
  - name: python
    id: "flake8"
    entrypoint: python
    args: ["-m", "flake8", "src", "--max-line-length=127"]
  - name: python
    id: "pytest"
    entrypoint: python
    env: ['PYTHONPATH=../app']
    dir: "src/unit_tests"
    args: ["-m", "pytest", "--cov=../app", "."]
  - name: python
    id: "coverage"
    dir: "src/unit_tests"
    entrypoint: python
    args: ["-m", "coverage", "report", "--fail-under=90"]
  - name: docker
    id: build_and_push
    entrypoint: sh
    args:
      - '-c'
      - |
        docker build -t "europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$SHORT_SHA" .
        docker push "europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$SHORT_SHA"
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'sds', '--image', 'europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$SHORT_SHA',
            '--region', 'europe-west2' ]
options:
  logging: CLOUD_LOGGING_ONLY