steps:
  - name: gcr.io/cloud-builders/docker
    id: "docker build and push"
    entrypoint: sh
    args:
      - "-c"
      - |
        docker build --cache-from "europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:latest" -t "europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:${SHORT_SHA}" -t "europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:latest" .
        docker push "europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:${SHORT_SHA}"
        docker push "europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:latest"
        
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Show image vulnerabilities (ons-sds-dev only)"
    entrypoint: bash
    args:
      - "-c"
      - |
        if [ ${PROJECT_ID} == "ons-sds-dev" ]
        then
          gcloud artifacts vulnerabilities list europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:latest \
            --format=json > /workspace/vulnerability_report
        else
          echo "Step not run for ${PROJECT_ID}"
        fi

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Check for critical vulnerabilities (ons-sds-dev only)"
    entrypoint: bash
    args:
      - "-c"
      - |
        if [ ${PROJECT_ID} == "ons-sds-dev" ]
        then
          apt-get -y update && apt-get install -y jq
          if jq -e '.[] | select( .vulnerability.effectiveSeverity == "CRITICAL")' /workspace/vulnerability_report > /dev/null; then
            echo "Error: Critical vulnerability found with image"
            exit 1
          fi
        else
          echo "Step not run for ${PROJECT_ID}"
        fi

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Run container"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "sds",
        "--no-invoker-iam-check",
        "--image",
        "europe-west2-docker.pkg.dev/${PROJECT_ID}/sds/sds:${SHORT_SHA}",
        "--region",
        "europe-west2",
        "--allow-unauthenticated",
        "--ingress",
        "internal-and-cloud-load-balancing",
        "--update-env-vars",
        "SDS_APPLICATION_VERSION=development",
        "--cpu-boost",
        "--session-affinity",
        "--min-instances",
        "1",
        "--max-instances",
        "100",
        "--concurrency",
        "1",
      ]

  - name: python:3.13
    id: "Run integration test"
    entrypoint: sh
    args:
      - "-c"
      - |
        export CONF='cloudbuild-int-tests'
        export LOG_LEVEL=${_LOG_LEVEL}
        export PROJECT_ID=${PROJECT_ID}
        export SCHEMA_BUCKET_NAME=${_SCHEMA_BUCKET_NAME}
        export PUBLISH_SCHEMA_TOPIC_ID=${_PUBLISH_SCHEMA_TOPIC_ID}
        export API_URL=${_API_URL}
        export SURVEY_MAP_URL=${_SURVEY_MAP_URL}
        export FIRESTORE_DB_NAME=${_FIRESTORE_DB_NAME}
        export SECRET_ID=iap-secret
        export URL_SCHEME=''
        pip install --upgrade pip --user
        pip install uv
        uv sync
        uv run python -m pytest --order-scope=module tests/integration_tests -vv -W ignore::DeprecationWarning

options:
  logging: CLOUD_LOGGING_ONLY