steps:
  - name: python
    id: "Setup Python"
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt" , "--user"]
  - name: python
    id: "Lint"
    entrypoint: python
    args: ["-m", "black", ".", "--check"]