steps:
  - name: python
    id: "Setup Python"
    entrypoint: pip
    args: [ "install", "-r", "requirements.txt" , "--user"]
  - name: python
    id: "black"
    entrypoint: python
    args: ["-m", "black", "src", "--check"]
  - name: python
    id: "isort"
    entrypoint: python
    args: ["-m", "isort", "src", "--check-only",  "--profile", "black"]
  - name: python
    id: "flake8"
    entrypoint: python
    args: ["-m", "flake8", "src", "--max-line-length=127"]
  - name: python
    id: "pytest"
    entrypoint: python
    env:
      - 'PYTHONPATH=src/app'
    args: ["-m", "pytest", "--cov=src/app", "src/unit_tests"]
  - name: python
    id: "coverage"
    entrypoint: python
    args: ["-m", "coverage", "report", "--fail-under=90"]
  - name: docker
    id: build_and_push
    entrypoint: sh
    args:
      - '-c'
      - |
        docker build -t "europe-west2-docker.pkg.dev/ons-sds-images/sds/sds:$SHORT_SHA" .
        docker push "europe-west2-docker.pkg.dev/ons-sds-images/sds/sds:$SHORT_SHA"