---
steps:
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    rev=$(git rev-parse --short HEAD)
    echo $rev > /workspace/short_sha
  id: 'get_short_sha'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull europe-west2-docker.pkg.dev/ons-sds-dev/sds/sds:$(cat /workspace/short_sha)
    docker tag europe-west2-docker.pkg.dev/ons-sds-dev/sds/sds:$(cat /workspace/short_sha) europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$TAG_NAME
    docker tag europe-west2-docker.pkg.dev/ons-sds-dev/sds/sds:$(cat /workspace/short_sha) europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$(cat /workspace/short_sha)
    docker push europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$TAG_NAME
    docker push europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$(cat /workspace/short_sha)
images:
- 'europe-west2-docker.pkg.dev/${_PROJECT}/sds/sds:$TAG_NAME'
options:
  logging: CLOUD_LOGGING_ONLY
