steps:
  - name: docker
    id: build_and_push
    entrypoint: sh
    args:
      - '-c'
      - |
        if [ $_ENV = "staging" ]; then
          docker build -t "eu.gcr.io/ons-sds-dns/sds:$SHORT_SHA" .
          docker push "eu.gcr.io/ons-sds-dns/sds:$SHORT_SHA"
        else
          echo "*************************************************************"
          echo "* Build not required                                        *"
          echo "*************************************************************"
        fi