version: "2.1"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.develop
    ports:
      - 3033:3033
    environment:
      - PORT=3033
      - CONF=docker-dev
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - PUBSUB_EMULATOR_HOST=firestore:8085
      - FIRESTORE_PROJECT_ID=mock-project-id
      - PUBSUB_PROJECT_ID=mock-project-id
      - LOG_LEVEL=DEBUG
      - PROJECT_ID=mock-project-id
      - PUBLISH_SCHEMA_TOPIC_ID=emulated-sds-schema-topic
    volumes:
      - ./app:/src
      - ./devtools:/devtools
    restart: on-failure
    depends_on:
      - firestore
    container_name: api-sds
  firestore:
    image: spine3/firebase-emulator
    ports:
      - 8080:8080
      - 4001:4001
      - 8085:8085
    environment:
      - GCP_PROJECT=mock-project-id
      - ENABLE_UI=true
    volumes:
      - ./devtools/firebase-emulator:/firebase
      - ./devtools/firebase-emulator:/firebase/baseline-data
    container_name: firestore-sds