FROM python:3.11
COPY src/app src
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
ENV PYTHONPATH=src
CMD ["uvicorn", "src.app:app", "--reload", "--host", "0.0.0.0", "--port", "${PORT}"]