apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/ons-cir-sandbox-ja/locust-tasks:latest
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 5c1388dc-25b4-4eb4-b747-a1e84aa6c1fe
  labels:
    cloud.googleapis.com/location: europe-west2
    run.googleapis.com/satisfiesPzs: 'true'
  name: locust-tasks
  namespace: '244163385647'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        client.knative.dev/user-image: gcr.io/ons-cir-sandbox-ja/locust-tasks:latest
        run.googleapis.com/client-name: cloud-console
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: AUTH_TOKEN
          value: ya29.a0AWY7CkkK3d9j4_LysJvVmlOut8vUzG22rV7-lxYU7JWKIO2zo6Ms23tBtlLRN2_0P6t5AXZTy-tWNpTni07LexlpaH2DtsUJss9QeIdHFaq7DXfGqosxssrhdVdekt9jR34rRqSUoFXNVw9H60Sw7lCRqH_46Cp609Zf3gaCgYKAe4SARASFQG1tDrpwYEcdZPN3FhkzGG1NkJFgg0173
        - name: CI_STORAGE_BUCKET_NAME
          value: ons-cir-sandbox-ja
        - name: DEFAULT_HOSTNAME
          value: ons-cir-sandbox-ja-api-gateway-3460kq3z.nw.gateway.dev
        - name: PROJECT_ID
          value: ons-cir-sandbox-ja
        image: gcr.io/ons-cir-sandbox-ja/locust-tasks:latest
        ports:
        - containerPort: 8089
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8089
          timeoutSeconds: 240
      serviceAccountName: 244163385647-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
