VERSION_PREFEX = "/V1/"

HEALTHCHECK_PATH = f"{VERSION_PREFEX}/healthcheck"

SCHEMA_PATH = f"{VERSION_PREFEX}/schema"

DATASET_PATH = f"{VERSION_PREFEX}/dataset"

SCHEMAS_PATH = f"{VERSION_PREFEX}/schemas"

DATASETS_PATH = f"{VERSION_PREFEX}/datasets"
