VERSION_PREFIX = "/v1/"

HEALTHCHECK_PATH = f"{VERSION_PREFIX}/healthcheck"

SCHEMA_PATH = f"{VERSION_PREFIX}/schema"

DATASET_PATH = f"{VERSION_PREFIX}/dataset"

SCHEMAS_PATH = f"{VERSION_PREFIX}/schemas"

DATASETS_PATH = f"{VERSION_PREFIX}/datasets"
